import type { Question } from "./types";

/**
 * Pool di domande di cultura generale — 120 domande su 11 sottocategorie.
 * Sottocategorie: geografia, storia-antica, storia-moderna, tecnologia,
 *                 politica-italia, grammatica-italiana, matematica,
 *                 fisica-chimica, arte, musica, religione
 */
export const generalQuestions: Question[] = [

  // ════════════════════════════════════════════════════════════════════════
  // GEOGRAFIA (12)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_004",
    category: "general",
    subcategory: "geografia",
    text: "Qual è la capitale dell'Australia?",
    answers: [
      { id: "A", text: "Sydney" },
      { id: "B", text: "Canberra" },
      { id: "C", text: "Melbourne" },
      { id: "D", text: "Brisbane" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Canberra è la capitale dell'Australia, non Sydney come molti credono!",
  },
  {
    id: "gen_007",
    category: "general",
    subcategory: "geografia",
    text: "Qual è il fiume più lungo del mondo?",
    answers: [
      { id: "A", text: "Amazzonia" },
      { id: "B", text: "Mississippi" },
      { id: "C", text: "Congo" },
      { id: "D", text: "Nilo" },
    ],
    correctAnswerIds: ["D"],
    explanation:
      "Il Nilo, con circa 6.650 km, è tradizionalmente considerato il fiume più lungo del mondo.",
  },
  {
    id: "gen_009",
    category: "general",
    subcategory: "geografia",
    text: "In quale paese si trova Machu Picchu?",
    answers: [
      { id: "A", text: "Colombia" },
      { id: "B", text: "Ecuador" },
      { id: "C", text: "Perù" },
      { id: "D", text: "Bolivia" },
    ],
    correctAnswerIds: ["C"],
    explanation:
      "Machu Picchu è un'antica città inca situata sulle Ande in Perù, a circa 2.430 m di altitudine.",
  },
  {
    id: "gen_014",
    category: "general",
    subcategory: "geografia",
    text: "Qual è l'oceano più grande del mondo?",
    answers: [
      { id: "A", text: "Pacifico" },
      { id: "B", text: "Atlantico" },
      { id: "C", text: "Indiano" },
      { id: "D", text: "Artico" },
    ],
    correctAnswerIds: ["A"],
    explanation: "L'Oceano Pacifico copre circa il 46% della superficie acquatica della Terra.",
  },
  {
    id: "gen_017",
    category: "general",
    subcategory: "geografia",
    text: "Quanti continenti ci sono sulla Terra?",
    answers: [
      { id: "A", text: "5" },
      { id: "B", text: "6" },
      { id: "C", text: "7" },
      { id: "D", text: "8" },
    ],
    correctAnswerIds: ["C"],
    explanation:
      "I 7 continenti sono: Africa, Antartide, Asia, Australia/Oceania, Europa, America del Nord, America del Sud.",
  },
  {
    id: "gen_019",
    category: "general",
    subcategory: "geografia",
    text: "Qual è la moneta ufficiale del Giappone?",
    answers: [
      { id: "A", text: "Yuan" },
      { id: "B", text: "Won" },
      { id: "C", text: "Baht" },
      { id: "D", text: "Yen" },
    ],
    correctAnswerIds: ["D"],
    explanation: "Lo Yen giapponese (¥) è una delle valute più scambiate al mondo.",
  },
  {
    id: "gen_020",
    category: "general",
    subcategory: "geografia",
    text: "Qual è il paese più grande del mondo per superficie?",
    answers: [
      { id: "A", text: "Russia" },
      { id: "B", text: "Canada" },
      { id: "C", text: "Cina" },
      { id: "D", text: "USA" },
    ],
    correctAnswerIds: ["A"],
    explanation:
      "La Russia copre circa 17 milioni di km², oltre il doppio del Canada che è al secondo posto.",
  },
  {
    id: "gen_024",
    category: "general",
    subcategory: "geografia",
    text: "Qual è la montagna più alta del mondo?",
    answers: [
      { id: "A", text: "K2" },
      { id: "B", text: "Monte Bianco" },
      { id: "C", text: "Kilimanjaro" },
      { id: "D", text: "Everest" },
    ],
    correctAnswerIds: ["D"],
    explanation: "L'Everest, con i suoi 8.849 m, è la montagna più alta del mondo. Si trova sull'Himalaya.",
  },
  {
    id: "gen_025",
    category: "general",
    subcategory: "geografia",
    text: "Qual è la capitale del Brasile?",
    answers: [
      { id: "A", text: "Rio de Janeiro" },
      { id: "B", text: "San Paolo" },
      { id: "C", text: "Brasilia" },
      { id: "D", text: "Salvador" },
    ],
    correctAnswerIds: ["C"],
    explanation: "Brasilia è la capitale del Brasile dal 1960. Molti pensano sia Rio de Janeiro, ma si sbagliano!",
  },
  {
    id: "gen_032",
    category: "general",
    subcategory: "geografia",
    text: "Qual è la capitale della Germania?",
    answers: [
      { id: "A", text: "Berlino" },
      { id: "B", text: "Monaco" },
      { id: "C", text: "Amburgo" },
      { id: "D", text: "Francoforte" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Berlino è la capitale e la città più grande della Germania con circa 3,7 milioni di abitanti.",
  },
  {
    id: "gen_037",
    category: "general",
    subcategory: "geografia",
    text: "Qual è il vulcano più alto d'Europa?",
    answers: [
      { id: "A", text: "Vesuvio" },
      { id: "B", text: "Stromboli" },
      { id: "C", text: "Etna" },
      { id: "D", text: "Vulcano" },
    ],
    correctAnswerIds: ["C"],
    explanation: "L'Etna, in Sicilia, con i suoi circa 3.340 m è il vulcano più alto d'Europa ed è ancora attivo.",
  },
  {
    id: "gen_038",
    category: "general",
    subcategory: "geografia",
    text: "In quale paese si trova il Canale di Panama?",
    answers: [
      { id: "A", text: "Colombia" },
      { id: "B", text: "Costa Rica" },
      { id: "C", text: "Nicaragua" },
      { id: "D", text: "Panama" },
    ],
    correctAnswerIds: ["D"],
    explanation:
      "Il Canale di Panama collega l'Oceano Pacifico all'Oceano Atlantico attraverso il paese di Panama.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // STORIA ANTICA (3)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_041",
    category: "general",
    subcategory: "storia-antica",
    text: "Chi fu il primo imperatore romano?",
    answers: [
      { id: "A", text: "Giulio Cesare" },
      { id: "B", text: "Augusto" },
      { id: "C", text: "Nerone" },
      { id: "D", text: "Traiano" },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "Augusto (Caio Ottavio Augusto) fu il primo imperatore di Roma dal 27 a.C. Giulio Cesare era un dittatore, non un imperatore.",
  },
  {
    id: "gen_042",
    category: "general",
    subcategory: "storia-antica",
    text: "In quale anno, secondo la tradizione, fu fondata Roma?",
    answers: [
      { id: "A", text: "510 a.C." },
      { id: "B", text: "753 a.C." },
      { id: "C", text: "264 a.C." },
      { id: "D", text: "146 a.C." },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "Secondo la tradizione, Roma fu fondata da Romolo nel 753 a.C. il 21 aprile — il Natale di Roma.",
  },
  {
    id: "gen_043",
    category: "general",
    subcategory: "storia-antica",
    text: "Quale civiltà costruì le piramidi di Giza?",
    answers: [
      { id: "A", text: "Romani" },
      { id: "B", text: "Greci" },
      { id: "C", text: "Sumeri" },
      { id: "D", text: "Egizi" },
    ],
    correctAnswerIds: ["D"],
    explanation:
      "Le piramidi di Giza furono costruite dagli antichi Egizi circa 4.500 anni fa come tombe per i faraoni.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // STORIA MODERNA (7)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_003",
    category: "general",
    subcategory: "storia-moderna",
    text: "In quale anno l'uomo è arrivato sulla Luna per la prima volta?",
    answers: [
      { id: "A", text: "1969" },
      { id: "B", text: "1965" },
      { id: "C", text: "1972" },
      { id: "D", text: "1961" },
    ],
    correctAnswerIds: ["A"],
    explanation:
      "Il 20 luglio 1969, Neil Armstrong fu il primo uomo a camminare sulla Luna con la missione Apollo 11.",
  },
  {
    id: "gen_013",
    category: "general",
    subcategory: "storia-moderna",
    text: "Chi ha scoperto la penicillina?",
    answers: [
      { id: "A", text: "Louis Pasteur" },
      { id: "B", text: "Marie Curie" },
      { id: "C", text: "Alexander Fleming" },
      { id: "D", text: "Robert Koch" },
    ],
    correctAnswerIds: ["C"],
    explanation:
      "Alexander Fleming scoprì la penicillina nel 1928 quasi per caso, osservando una muffa che uccideva i batteri.",
  },
  {
    id: "gen_015",
    category: "general",
    subcategory: "storia-moderna",
    text: "In quale anno è caduto il Muro di Berlino?",
    answers: [
      { id: "A", text: "1987" },
      { id: "B", text: "1990" },
      { id: "C", text: "1988" },
      { id: "D", text: "1989" },
    ],
    correctAnswerIds: ["D"],
    explanation: "Il Muro di Berlino cadde il 9 novembre 1989, segnando la fine della Guerra Fredda.",
  },
  {
    id: "gen_016",
    category: "general",
    subcategory: "storia-moderna",
    text: "Quale sport si gioca a Wimbledon?",
    answers: [
      { id: "A", text: "Golf" },
      { id: "B", text: "Tennis" },
      { id: "C", text: "Cricket" },
      { id: "D", text: "Polo" },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "Wimbledon è il torneo di tennis più antico e prestigioso del mondo, fondato nel 1877.",
  },
  {
    id: "gen_029",
    category: "general",
    subcategory: "storia-moderna",
    text: "In quale anno finì la Seconda Guerra Mondiale?",
    answers: [
      { id: "A", text: "1943" },
      { id: "B", text: "1944" },
      { id: "C", text: "1945" },
      { id: "D", text: "1946" },
    ],
    correctAnswerIds: ["C"],
    explanation:
      "La Seconda Guerra Mondiale finì nel 1945: la Germania capitolò in maggio, il Giappone in settembre.",
  },
  {
    id: "gen_031",
    category: "general",
    subcategory: "storia-moderna",
    text: "Chi fu il primo essere umano a viaggiare nello spazio?",
    answers: [
      { id: "A", text: "Neil Armstrong" },
      { id: "B", text: "Yuri Gagarin" },
      { id: "C", text: "Buzz Aldrin" },
      { id: "D", text: "Alan Shepard" },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "Yuri Gagarin il 12 aprile 1961 completò un'orbita intorno alla Terra a bordo della Vostok 1.",
  },
  {
    id: "gen_040",
    category: "general",
    subcategory: "storia-moderna",
    text: "Da quale città proviene originariamente la pizza?",
    answers: [
      { id: "A", text: "Roma" },
      { id: "B", text: "Palermo" },
      { id: "C", text: "Napoli" },
      { id: "D", text: "Milano" },
    ],
    correctAnswerIds: ["C"],
    explanation:
      "La pizza nasce a Napoli nel XVIII secolo. La Margherita fu creata nel 1889 in onore della regina Margherita di Savoia.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // TECNOLOGIA (3)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_044",
    category: "general",
    subcategory: "tecnologia",
    text: "In quale anno fu lanciato il primo iPhone?",
    answers: [
      { id: "A", text: "2005" },
      { id: "B", text: "2007" },
      { id: "C", text: "2009" },
      { id: "D", text: "2010" },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "Steve Jobs presentò il primo iPhone il 9 gennaio 2007, rivoluzionando il mercato degli smartphone.",
  },
  {
    id: "gen_045",
    category: "general",
    subcategory: "tecnologia",
    text: "Chi ha fondato Amazon?",
    answers: [
      { id: "A", text: "Steve Jobs" },
      { id: "B", text: "Elon Musk" },
      { id: "C", text: "Jeff Bezos" },
      { id: "D", text: "Mark Zuckerberg" },
    ],
    correctAnswerIds: ["C"],
    explanation:
      "Jeff Bezos fondò Amazon nel 1994 come libreria online. Oggi è uno dei marketplace più grandi al mondo.",
  },
  {
    id: "gen_046",
    category: "general",
    subcategory: "tecnologia",
    text: "Cosa significa l'acronimo HTML?",
    answers: [
      { id: "A", text: "HyperText Markup Language" },
      { id: "B", text: "High Tech Machine Learning" },
      { id: "C", text: "HyperText Modern Layout" },
      { id: "D", text: "High Transfer Multimedia Language" },
    ],
    correctAnswerIds: ["A"],
    explanation:
      "HTML (HyperText Markup Language) è il linguaggio di markup standard per creare pagine web.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // POLITICA ITALIA (4)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_005",
    category: "general",
    subcategory: "politica-italia",
    text: "Quante regioni ha l'Italia?",
    answers: [
      { id: "A", text: "18" },
      { id: "B", text: "22" },
      { id: "C", text: "20" },
      { id: "D", text: "15" },
    ],
    correctAnswerIds: ["C"],
    explanation: "L'Italia è divisa in 20 regioni, di cui 5 a statuto speciale.",
  },
  {
    id: "gen_027",
    category: "general",
    subcategory: "politica-italia",
    text: "Quante stelle ha la bandiera dell'Unione Europea?",
    answers: [
      { id: "A", text: "10" },
      { id: "B", text: "15" },
      { id: "C", text: "24" },
      { id: "D", text: "12" },
    ],
    correctAnswerIds: ["D"],
    explanation:
      "La bandiera EU ha sempre 12 stelle dorate, indipendentemente dal numero di paesi membri.",
  },
  {
    id: "gen_049",
    category: "general",
    subcategory: "politica-italia",
    text: "In quale anno fu proclamata la Repubblica Italiana?",
    answers: [
      { id: "A", text: "1943" },
      { id: "B", text: "1945" },
      { id: "C", text: "1946" },
      { id: "D", text: "1948" },
    ],
    correctAnswerIds: ["C"],
    explanation:
      "Il referendum del 2 giugno 1946 sancì la scelta della Repubblica. Da allora il 2 giugno è festa nazionale.",
  },
  {
    id: "gen_050",
    category: "general",
    subcategory: "politica-italia",
    text: "Chi è il capo dello Stato in Italia?",
    answers: [
      { id: "A", text: "Il Presidente del Consiglio" },
      { id: "B", text: "Il Presidente della Repubblica" },
      { id: "C", text: "Il Re" },
      { id: "D", text: "Il Presidente del Senato" },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "Il Presidente della Repubblica è il capo dello Stato. Il Presidente del Consiglio è il capo del governo.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // GRAMMATICA ITALIANA (3)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_006",
    category: "general",
    subcategory: "grammatica-italiana",
    text: "Chi ha scritto la Divina Commedia?",
    answers: [
      { id: "A", text: "Dante Alighieri" },
      { id: "B", text: "Francesco Petrarca" },
      { id: "C", text: "Giovanni Boccaccio" },
      { id: "D", text: "Ludovico Ariosto" },
    ],
    correctAnswerIds: ["A"],
    explanation:
      "Dante Alighieri scrisse la Divina Commedia tra il 1304 e il 1321, capolavoro assoluto della letteratura italiana.",
  },
  {
    id: "gen_047",
    category: "general",
    subcategory: "grammatica-italiana",
    text: "Quante lettere ha l'alfabeto italiano?",
    answers: [
      { id: "A", text: "26" },
      { id: "B", text: "21" },
      { id: "C", text: "23" },
      { id: "D", text: "28" },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "L'alfabeto italiano ha 21 lettere. Mancano J, K, W, X, Y rispetto all'alfabeto latino internazionale.",
  },
  {
    id: "gen_048",
    category: "general",
    subcategory: "grammatica-italiana",
    text: "Quale articolo determinativo si usa davanti alla parola 'zaino'?",
    answers: [
      { id: "A", text: "il" },
      { id: "B", text: "lo" },
      { id: "C", text: "la" },
      { id: "D", text: "l'" },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "Si usa 'lo' davanti a parole maschili che iniziano per z, s+consonante, gn, pn, ps, x, y. Quindi: 'lo zaino'.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // MATEMATICA (4)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_012",
    category: "general",
    subcategory: "matematica",
    text: "Quanti lati ha un dodecagono?",
    answers: [
      { id: "A", text: "10" },
      { id: "B", text: "12" },
      { id: "C", text: "14" },
      { id: "D", text: "16" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Il dodecagono ha 12 lati. Dodeca- viene dal greco e significa 12.",
  },
  {
    id: "gen_022",
    category: "general",
    subcategory: "matematica",
    text: "Quanti giorni ha un anno bisestile?",
    answers: [
      { id: "A", text: "365" },
      { id: "B", text: "367" },
      { id: "C", text: "366" },
      { id: "D", text: "364" },
    ],
    correctAnswerIds: ["C"],
    explanation: "Un anno bisestile ha 366 giorni grazie al giorno extra del 29 febbraio.",
  },
  {
    id: "gen_033",
    category: "general",
    subcategory: "matematica",
    text: "Quanti mesi dell'anno hanno 31 giorni?",
    answers: [
      { id: "A", text: "5" },
      { id: "B", text: "6" },
      { id: "C", text: "7" },
      { id: "D", text: "8" },
    ],
    correctAnswerIds: ["C"],
    explanation:
      "I mesi con 31 giorni sono: gennaio, marzo, maggio, luglio, agosto, ottobre, dicembre.",
  },
  {
    id: "gen_051",
    category: "general",
    subcategory: "matematica",
    text: "Quanti numeri primi ci sono tra 1 e 10?",
    answers: [
      { id: "A", text: "3" },
      { id: "B", text: "4" },
      { id: "C", text: "5" },
      { id: "D", text: "6" },
    ],
    correctAnswerIds: ["B"],
    explanation: "I numeri primi tra 1 e 10 sono: 2, 3, 5, 7 — quattro in totale.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // FISICA E CHIMICA / SCIENZE (6)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_001",
    category: "general",
    subcategory: "fisica-chimica",
    text: "Quale pianeta è conosciuto come il Pianeta Rosso?",
    answers: [
      { id: "A", text: "Venere" },
      { id: "B", text: "Marte" },
      { id: "C", text: "Giove" },
      { id: "D", text: "Saturno" },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "Marte è chiamato Pianeta Rosso per il colore della sua superficie, dovuto all'ossido di ferro.",
  },
  {
    id: "gen_011",
    category: "general",
    subcategory: "fisica-chimica",
    text: "Qual è il simbolo chimico dell'oro?",
    answers: [
      { id: "A", text: "Or" },
      { id: "B", text: "Ag" },
      { id: "C", text: "Cu" },
      { id: "D", text: "Au" },
    ],
    correctAnswerIds: ["D"],
    explanation: "Il simbolo dell'oro è Au, dal latino Aurum.",
  },
  {
    id: "gen_028",
    category: "general",
    subcategory: "fisica-chimica",
    text: "Qual è la formula chimica dell'acqua?",
    answers: [
      { id: "A", text: "HO₂" },
      { id: "B", text: "H₂O" },
      { id: "C", text: "H₃O" },
      { id: "D", text: "OH₂" },
    ],
    correctAnswerIds: ["B"],
    explanation: "H₂O: due atomi di idrogeno e uno di ossigeno. La molecola più importante sulla Terra.",
  },
  {
    id: "gen_030",
    category: "general",
    subcategory: "fisica-chimica",
    text: "Quale pianeta ha gli anelli più famosi del sistema solare?",
    answers: [
      { id: "A", text: "Urano" },
      { id: "B", text: "Nettuno" },
      { id: "C", text: "Giove" },
      { id: "D", text: "Saturno" },
    ],
    correctAnswerIds: ["D"],
    explanation:
      "Gli anelli di Saturno sono composti principalmente da ghiaccio e roccia, e si estendono per migliaia di km.",
  },
  {
    id: "gen_034",
    category: "general",
    subcategory: "fisica-chimica",
    text: "Qual è il mammifero terrestre più veloce del mondo?",
    answers: [
      { id: "A", text: "Ghepardo" },
      { id: "B", text: "Leone" },
      { id: "C", text: "Tigre" },
      { id: "D", text: "Antilope" },
    ],
    correctAnswerIds: ["A"],
    explanation:
      "Il ghepardo può raggiungere i 110 km/h in brevi scatti. È il più veloce sulla terraferma.",
  },
  {
    id: "gen_036",
    category: "general",
    subcategory: "fisica-chimica",
    text: "Quanti colori ha l'arcobaleno?",
    answers: [
      { id: "A", text: "5" },
      { id: "B", text: "6" },
      { id: "C", text: "7" },
      { id: "D", text: "8" },
    ],
    correctAnswerIds: ["C"],
    explanation: "L'arcobaleno ha 7 colori: rosso, arancione, giallo, verde, azzurro, indaco, violetto.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // ARTE E LETTERATURA (5)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_002",
    category: "general",
    subcategory: "arte",
    text: "Chi ha affrescato la Cappella Sistina?",
    answers: [
      { id: "A", text: "Leonardo da Vinci" },
      { id: "B", text: "Raffaello" },
      { id: "C", text: "Michelangelo" },
      { id: "D", text: "Botticelli" },
    ],
    correctAnswerIds: ["C"],
    explanation:
      "Michelangelo dipinse la Cappella Sistina tra il 1508 e il 1512 su commissione di Papa Giulio II.",
  },
  {
    id: "gen_021",
    category: "general",
    subcategory: "arte",
    text: "Chi ha dipinto la Gioconda?",
    answers: [
      { id: "A", text: "Michelangelo" },
      { id: "B", text: "Leonardo da Vinci" },
      { id: "C", text: "Raffaello" },
      { id: "D", text: "Caravaggio" },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "Leonardo da Vinci dipinse la Gioconda (Mona Lisa) tra il 1503 e il 1519. È esposta al Louvre di Parigi.",
  },
  {
    id: "gen_023",
    category: "general",
    subcategory: "arte",
    text: "Chi scrisse Romeo e Giulietta?",
    answers: [
      { id: "A", text: "William Shakespeare" },
      { id: "B", text: "Charles Dickens" },
      { id: "C", text: "Jane Austen" },
      { id: "D", text: "Oscar Wilde" },
    ],
    correctAnswerIds: ["A"],
    explanation:
      "William Shakespeare scrisse Romeo e Giulietta intorno al 1595, la storia d'amore più famosa della letteratura mondiale.",
  },
  {
    id: "gen_026",
    category: "general",
    subcategory: "arte",
    text: "Chi è l'autrice della saga di Harry Potter?",
    answers: [
      { id: "A", text: "J.K. Rowling" },
      { id: "B", text: "Roald Dahl" },
      { id: "C", text: "C.S. Lewis" },
      { id: "D", text: "Philip Pullman" },
    ],
    correctAnswerIds: ["A"],
    explanation: "J.K. Rowling ha scritto i 7 libri di Harry Potter tra il 1997 e il 2007.",
  },
  {
    id: "gen_035",
    category: "general",
    subcategory: "arte",
    text: "Dove si trova il David di Michelangelo?",
    answers: [
      { id: "A", text: "Roma" },
      { id: "B", text: "Milano" },
      { id: "C", text: "Firenze" },
      { id: "D", text: "Napoli" },
    ],
    correctAnswerIds: ["C"],
    explanation: "Il David di Michelangelo si trova alla Galleria dell'Accademia di Firenze dal 1873.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // MUSICA (4)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_008",
    category: "general",
    subcategory: "musica",
    text: "Quante corde ha una chitarra classica?",
    answers: [
      { id: "A", text: "4" },
      { id: "B", text: "6" },
      { id: "C", text: "8" },
      { id: "D", text: "12" },
    ],
    correctAnswerIds: ["B"],
    explanation: "La chitarra classica ha 6 corde: Mi, La, Re, Sol, Si, Mi.",
  },
  {
    id: "gen_010",
    category: "general",
    subcategory: "musica",
    text: "Chi ha composto la Quinta Sinfonia?",
    answers: [
      { id: "A", text: "Beethoven" },
      { id: "B", text: "Mozart" },
      { id: "C", text: "Bach" },
      { id: "D", text: "Vivaldi" },
    ],
    correctAnswerIds: ["A"],
    explanation:
      'Ludwig van Beethoven compose la Quinta Sinfonia, celebre per il suo inizio "ta-ta-ta-taaaa".',
  },
  {
    id: "gen_018",
    category: "general",
    subcategory: "musica",
    text: "Chi ha composto La Traviata?",
    answers: [
      { id: "A", text: "Giuseppe Verdi" },
      { id: "B", text: "Giacomo Puccini" },
      { id: "C", text: "Gioachino Rossini" },
      { id: "D", text: "Gaetano Donizetti" },
    ],
    correctAnswerIds: ["A"],
    explanation:
      "La Traviata fu composta da Giuseppe Verdi nel 1853, basata sul romanzo La signora delle camelie.",
  },
  {
    id: "gen_039",
    category: "general",
    subcategory: "musica",
    text: "Chi ha cantato la celebre canzone 'Azzurro'?",
    answers: [
      { id: "A", text: "Lucio Battisti" },
      { id: "B", text: "Adriano Celentano" },
      { id: "C", text: "Mina" },
      { id: "D", text: "Lucio Dalla" },
    ],
    correctAnswerIds: ["B"],
    explanation:
      "Adriano Celentano cantò Azzurro nel 1968, una delle canzoni italiane più iconiche di sempre.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // EXTRA PER ARRIVARE AD ALMENO 5 DOMANDE PER MATERIA
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_052",
    category: "general",
    subcategory: "storia-antica",
    text: "Quale popolo fondò la città di Cartagine?",
    answers: [
      { id: "A", text: "Fenici" },
      { id: "B", text: "Romani" },
      { id: "C", text: "Etruschi" },
      { id: "D", text: "Macedoni" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Cartagine fu fondata dai Fenici, probabilmente da coloni provenienti da Tiro.",
  },
  {
    id: "gen_053",
    category: "general",
    subcategory: "storia-antica",
    text: "Chi guidò i Macedoni alla conquista dell'Impero persiano?",
    answers: [
      { id: "A", text: "Leonida" },
      { id: "B", text: "Alessandro Magno" },
      { id: "C", text: "Pericle" },
      { id: "D", text: "Annibale" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Alessandro Magno conquistò gran parte dell'Impero persiano nel IV secolo a.C.",
  },
  {
    id: "gen_054",
    category: "general",
    subcategory: "tecnologia",
    text: "Che cosa indica la sigla URL?",
    answers: [
      { id: "A", text: "Universal Resource Locator" },
      { id: "B", text: "Uniform Resource Locator" },
      { id: "C", text: "Unique Router Link" },
      { id: "D", text: "User Remote Login" },
    ],
    correctAnswerIds: ["B"],
    explanation: "URL significa Uniform Resource Locator: è l'indirizzo di una risorsa sul web.",
  },
  {
    id: "gen_055",
    category: "general",
    subcategory: "tecnologia",
    text: "Quale componente è considerato il 'cervello' del computer?",
    answers: [
      { id: "A", text: "Hard disk" },
      { id: "B", text: "RAM" },
      { id: "C", text: "CPU" },
      { id: "D", text: "Scheda audio" },
    ],
    correctAnswerIds: ["C"],
    explanation: "La CPU esegue le istruzioni principali del computer.",
  },
  {
    id: "gen_056",
    category: "general",
    subcategory: "politica-italia",
    text: "Quanti rami ha il Parlamento italiano?",
    answers: [
      { id: "A", text: "Uno" },
      { id: "B", text: "Due" },
      { id: "C", text: "Tre" },
      { id: "D", text: "Quattro" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Il Parlamento italiano è formato da Camera dei deputati e Senato della Repubblica.",
  },
  {
    id: "gen_057",
    category: "general",
    subcategory: "grammatica-italiana",
    text: "Quale tra queste parole è un avverbio?",
    answers: [
      { id: "A", text: "Veloce" },
      { id: "B", text: "Velocemente" },
      { id: "C", text: "Velocità" },
      { id: "D", text: "Velocista" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Velocemente è un avverbio di modo: spiega come si svolge un'azione.",
  },
  {
    id: "gen_058",
    category: "general",
    subcategory: "grammatica-italiana",
    text: "In analisi grammaticale, che cos'è 'noi'?",
    answers: [
      { id: "A", text: "Articolo" },
      { id: "B", text: "Pronome personale" },
      { id: "C", text: "Aggettivo" },
      { id: "D", text: "Congiunzione" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Noi è un pronome personale di prima persona plurale.",
  },
  {
    id: "gen_059",
    category: "general",
    subcategory: "matematica",
    text: "Quanto fa 12 x 12?",
    answers: [
      { id: "A", text: "124" },
      { id: "B", text: "132" },
      { id: "C", text: "144" },
      { id: "D", text: "156" },
    ],
    correctAnswerIds: ["C"],
    explanation: "12 moltiplicato per 12 fa 144.",
  },
  {
    id: "gen_060",
    category: "general",
    subcategory: "musica",
    text: "Quante corde ha normalmente una chitarra classica?",
    answers: [
      { id: "A", text: "4" },
      { id: "B", text: "5" },
      { id: "C", text: "6" },
      { id: "D", text: "7" },
    ],
    correctAnswerIds: ["C"],
    explanation: "La chitarra classica normalmente ha 6 corde.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // RELIGIONE (5)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_061",
    category: "general",
    subcategory: "religione",
    text: "Secondo la ricerca storica, in quale area visse Gesù di Nazaret?",
    answers: [
      { id: "A", text: "Galilea e Giudea" },
      { id: "B", text: "Grecia e Macedonia" },
      { id: "C", text: "Egitto e Nubia" },
      { id: "D", text: "Persia e Media" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Gesù di Nazaret è collocato storicamente nella Palestina del I secolo, soprattutto tra Galilea e Giudea.",
  },
  {
    id: "gen_062",
    category: "general",
    subcategory: "religione",
    text: "Qual è il testo sacro principale dell'Islam?",
    answers: [
      { id: "A", text: "Corano" },
      { id: "B", text: "Bibbia" },
      { id: "C", text: "Veda" },
      { id: "D", text: "Tripitaka" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Il Corano è il testo sacro principale dell'Islam.",
  },
  {
    id: "gen_063",
    category: "general",
    subcategory: "religione",
    text: "In quale religione è centrale la figura del Buddha?",
    answers: [
      { id: "A", text: "Ebraismo" },
      { id: "B", text: "Buddismo" },
      { id: "C", text: "Cristianesimo" },
      { id: "D", text: "Sikhismo" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Il Buddha è la figura centrale del Buddismo.",
  },
  {
    id: "gen_064",
    category: "general",
    subcategory: "religione",
    text: "Come si chiama il giorno di riposo settimanale nella tradizione ebraica?",
    answers: [
      { id: "A", text: "Ramadan" },
      { id: "B", text: "Shabbat" },
      { id: "C", text: "Diwali" },
      { id: "D", text: "Vesak" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Lo Shabbat è il giorno di riposo della tradizione ebraica, dal tramonto del venerdì al sabato sera.",
  },
  {
    id: "gen_065",
    category: "general",
    subcategory: "religione",
    text: "Quale festa induista è nota anche come festa delle luci?",
    answers: [
      { id: "A", text: "Diwali" },
      { id: "B", text: "Hanukkah" },
      { id: "C", text: "Pasqua" },
      { id: "D", text: "Eid al-Fitr" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Diwali è una delle principali feste induiste ed è spesso chiamata festa delle luci.",
  },

  // ════════════════════════════════════════════════════════════════════════
  // EXTRA +5 PER OGNI MATERIA
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "gen_066",
    category: "general",
    subcategory: "geografia",
    text: "Qual è la capitale del Canada?",
    answers: [
      { id: "A", text: "Toronto" },
      { id: "B", text: "Ottawa" },
      { id: "C", text: "Vancouver" },
      { id: "D", text: "Montreal" },
    ],
    correctAnswerIds: ["B"],
    explanation: "La capitale del Canada è Ottawa, non Toronto che è la città più popolosa.",
  },
  {
    id: "gen_067",
    category: "general",
    subcategory: "geografia",
    text: "In quale continente si trova il deserto del Kalahari?",
    answers: [
      { id: "A", text: "Africa" },
      { id: "B", text: "Asia" },
      { id: "C", text: "Australia" },
      { id: "D", text: "Sud America" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Il Kalahari si estende nell'Africa australe, soprattutto tra Botswana, Namibia e Sudafrica.",
  },
  {
    id: "gen_068",
    category: "general",
    subcategory: "geografia",
    text: "Quale stretto separa l'Europa dall'Africa tra Spagna e Marocco?",
    answers: [
      { id: "A", text: "Stretto di Bering" },
      { id: "B", text: "Stretto di Gibilterra" },
      { id: "C", text: "Stretto di Messina" },
      { id: "D", text: "Bosforo" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Lo Stretto di Gibilterra collega Atlantico e Mediterraneo e separa Spagna e Marocco.",
  },
  {
    id: "gen_069",
    category: "general",
    subcategory: "geografia",
    text: "Qual è il lago più grande d'Italia?",
    answers: [
      { id: "A", text: "Lago di Como" },
      { id: "B", text: "Lago Maggiore" },
      { id: "C", text: "Lago di Garda" },
      { id: "D", text: "Lago Trasimeno" },
    ],
    correctAnswerIds: ["C"],
    explanation: "Il Lago di Garda è il lago italiano più grande per superficie.",
  },
  {
    id: "gen_070",
    category: "general",
    subcategory: "geografia",
    text: "Quale paese ha la forma geografica spesso paragonata a uno stivale?",
    answers: [
      { id: "A", text: "Italia" },
      { id: "B", text: "Grecia" },
      { id: "C", text: "Portogallo" },
      { id: "D", text: "Norvegia" },
    ],
    correctAnswerIds: ["A"],
    explanation: "La penisola italiana è famosa per la sua forma a stivale.",
  },
  {
    id: "gen_071",
    category: "general",
    subcategory: "storia-antica",
    text: "Quale generale cartaginese attraversò le Alpi con gli elefanti?",
    answers: [
      { id: "A", text: "Annibale" },
      { id: "B", text: "Scipione" },
      { id: "C", text: "Cesare" },
      { id: "D", text: "Pirro" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Annibale attraversò le Alpi durante la seconda guerra punica per attaccare Roma.",
  },
  {
    id: "gen_072",
    category: "general",
    subcategory: "storia-antica",
    text: "Quale città greca era famosa per l'educazione militare dei suoi cittadini?",
    answers: [
      { id: "A", text: "Atene" },
      { id: "B", text: "Sparta" },
      { id: "C", text: "Corinto" },
      { id: "D", text: "Tebe" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Sparta era nota per la disciplina militare e l'addestramento dei cittadini fin da giovani.",
  },
  {
    id: "gen_073",
    category: "general",
    subcategory: "storia-antica",
    text: "Come si chiamava la grande arena romana destinata agli spettacoli dei gladiatori?",
    answers: [
      { id: "A", text: "Colosseo" },
      { id: "B", text: "Pantheon" },
      { id: "C", text: "Foro Romano" },
      { id: "D", text: "Circo Massimo" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Il Colosseo, o Anfiteatro Flavio, ospitava combattimenti e grandi spettacoli pubblici.",
  },
  {
    id: "gen_074",
    category: "general",
    subcategory: "storia-antica",
    text: "Quale scrittura usavano gli antichi Egizi per testi sacri e monumentali?",
    answers: [
      { id: "A", text: "Cuneiforme" },
      { id: "B", text: "Geroglifici" },
      { id: "C", text: "Alfabeto latino" },
      { id: "D", text: "Runico" },
    ],
    correctAnswerIds: ["B"],
    explanation: "I geroglifici erano il sistema di scrittura monumentale dell'antico Egitto.",
  },
  {
    id: "gen_075",
    category: "general",
    subcategory: "storia-antica",
    text: "Quale imperatore romano rese legale il cristianesimo con l'Editto di Milano?",
    answers: [
      { id: "A", text: "Nerone" },
      { id: "B", text: "Costantino" },
      { id: "C", text: "Augusto" },
      { id: "D", text: "Adriano" },
    ],
    correctAnswerIds: ["B"],
    explanation: "L'Editto di Milano del 313, legato a Costantino, concesse libertà di culto ai cristiani.",
  },
  {
    id: "gen_076",
    category: "general",
    subcategory: "storia-moderna",
    text: "Quale rivoluzione iniziò in Francia nel 1789?",
    answers: [
      { id: "A", text: "Rivoluzione industriale" },
      { id: "B", text: "Rivoluzione francese" },
      { id: "C", text: "Rivoluzione americana" },
      { id: "D", text: "Rivoluzione russa" },
    ],
    correctAnswerIds: ["B"],
    explanation: "La Rivoluzione francese iniziò nel 1789 e cambiò profondamente la storia europea.",
  },
  {
    id: "gen_077",
    category: "general",
    subcategory: "storia-moderna",
    text: "Chi era il leader del movimento per l'indipendenza dell'India basato sulla non violenza?",
    answers: [
      { id: "A", text: "Mahatma Gandhi" },
      { id: "B", text: "Nelson Mandela" },
      { id: "C", text: "Martin Luther King" },
      { id: "D", text: "Winston Churchill" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Gandhi guidò la lotta indiana contro il dominio britannico con metodi di resistenza non violenta.",
  },
  {
    id: "gen_078",
    category: "general",
    subcategory: "storia-moderna",
    text: "In quale secolo iniziò la Rivoluzione industriale in Inghilterra?",
    answers: [
      { id: "A", text: "XVI secolo" },
      { id: "B", text: "XVII secolo" },
      { id: "C", text: "XVIII secolo" },
      { id: "D", text: "XX secolo" },
    ],
    correctAnswerIds: ["C"],
    explanation: "La Rivoluzione industriale iniziò in Inghilterra nel XVIII secolo.",
  },
  {
    id: "gen_079",
    category: "general",
    subcategory: "storia-moderna",
    text: "Chi fu il primo presidente degli Stati Uniti?",
    answers: [
      { id: "A", text: "Thomas Jefferson" },
      { id: "B", text: "George Washington" },
      { id: "C", text: "Abraham Lincoln" },
      { id: "D", text: "Benjamin Franklin" },
    ],
    correctAnswerIds: ["B"],
    explanation: "George Washington fu il primo presidente degli Stati Uniti, in carica dal 1789.",
  },
  {
    id: "gen_080",
    category: "general",
    subcategory: "storia-moderna",
    text: "Quale organizzazione internazionale nacque dopo la Seconda Guerra Mondiale per promuovere la pace?",
    answers: [
      { id: "A", text: "ONU" },
      { id: "B", text: "NATO" },
      { id: "C", text: "Unione Europea" },
      { id: "D", text: "G7" },
    ],
    correctAnswerIds: ["A"],
    explanation: "L'Organizzazione delle Nazioni Unite nacque nel 1945 per favorire cooperazione e pace internazionale.",
  },
  {
    id: "gen_081",
    category: "general",
    subcategory: "tecnologia",
    text: "Cosa significa la sigla CPU?",
    answers: [
      { id: "A", text: "Central Processing Unit" },
      { id: "B", text: "Computer Power Utility" },
      { id: "C", text: "Central Program Update" },
      { id: "D", text: "Control Panel Unit" },
    ],
    correctAnswerIds: ["A"],
    explanation: "CPU significa Central Processing Unit, l'unità centrale che esegue le istruzioni del computer.",
  },
  {
    id: "gen_082",
    category: "general",
    subcategory: "tecnologia",
    text: "Quale azienda sviluppa il sistema operativo Android?",
    answers: [
      { id: "A", text: "Apple" },
      { id: "B", text: "Google" },
      { id: "C", text: "Microsoft" },
      { id: "D", text: "Samsung" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Android è sviluppato da Google, anche se viene usato da molti produttori di smartphone.",
  },
  {
    id: "gen_083",
    category: "general",
    subcategory: "tecnologia",
    text: "A cosa serve principalmente un browser web?",
    answers: [
      { id: "A", text: "Navigare su siti internet" },
      { id: "B", text: "Stampare documenti" },
      { id: "C", text: "Raffreddare il computer" },
      { id: "D", text: "Ricaricare la batteria" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Un browser, come Chrome, Safari o Firefox, permette di visitare e usare siti web.",
  },
  {
    id: "gen_084",
    category: "general",
    subcategory: "tecnologia",
    text: "Quale formato è comunemente usato per immagini fotografiche compresse?",
    answers: [
      { id: "A", text: "MP3" },
      { id: "B", text: "JPG" },
      { id: "C", text: "DOCX" },
      { id: "D", text: "ZIP" },
    ],
    correctAnswerIds: ["B"],
    explanation: "JPG o JPEG è uno dei formati più comuni per fotografie digitali compresse.",
  },
  {
    id: "gen_085",
    category: "general",
    subcategory: "tecnologia",
    text: "Che cosa indica il lucchetto accanto all'indirizzo di un sito web?",
    answers: [
      { id: "A", text: "Connessione HTTPS cifrata" },
      { id: "B", text: "Sito sempre gratuito" },
      { id: "C", text: "Computer senza virus" },
      { id: "D", text: "Pagina salvata offline" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Il lucchetto indica una connessione HTTPS cifrata tra browser e sito.",
  },
  {
    id: "gen_086",
    category: "general",
    subcategory: "politica-italia",
    text: "Qual è la sede della Camera dei deputati?",
    answers: [
      { id: "A", text: "Palazzo Madama" },
      { id: "B", text: "Palazzo Chigi" },
      { id: "C", text: "Montecitorio" },
      { id: "D", text: "Quirinale" },
    ],
    correctAnswerIds: ["C"],
    explanation: "La Camera dei deputati ha sede a Palazzo Montecitorio, a Roma.",
  },
  {
    id: "gen_087",
    category: "general",
    subcategory: "politica-italia",
    text: "Quale organo elegge il Presidente della Repubblica italiana?",
    answers: [
      { id: "A", text: "Solo il Governo" },
      { id: "B", text: "Il Parlamento in seduta comune con delegati regionali" },
      { id: "C", text: "Solo i cittadini con voto diretto" },
      { id: "D", text: "La Corte costituzionale" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Il Presidente della Repubblica viene eletto dal Parlamento in seduta comune, integrato da delegati regionali.",
  },
  {
    id: "gen_088",
    category: "general",
    subcategory: "politica-italia",
    text: "Come si chiama la legge fondamentale dello Stato italiano?",
    answers: [
      { id: "A", text: "Codice civile" },
      { id: "B", text: "Costituzione" },
      { id: "C", text: "Statuto comunale" },
      { id: "D", text: "Trattato di Roma" },
    ],
    correctAnswerIds: ["B"],
    explanation: "La Costituzione italiana è la legge fondamentale dello Stato.",
  },
  {
    id: "gen_089",
    category: "general",
    subcategory: "politica-italia",
    text: "Quale città ospita il Palazzo del Quirinale?",
    answers: [
      { id: "A", text: "Roma" },
      { id: "B", text: "Milano" },
      { id: "C", text: "Torino" },
      { id: "D", text: "Firenze" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Il Quirinale, sede del Presidente della Repubblica, si trova a Roma.",
  },
  {
    id: "gen_090",
    category: "general",
    subcategory: "politica-italia",
    text: "Quanti sono i colori della bandiera italiana?",
    answers: [
      { id: "A", text: "Due" },
      { id: "B", text: "Tre" },
      { id: "C", text: "Quattro" },
      { id: "D", text: "Cinque" },
    ],
    correctAnswerIds: ["B"],
    explanation: "La bandiera italiana è il tricolore: verde, bianco e rosso.",
  },
  {
    id: "gen_091",
    category: "general",
    subcategory: "grammatica-italiana",
    text: "Qual è il plurale corretto di 'ciliegia'?",
    answers: [
      { id: "A", text: "Ciliege" },
      { id: "B", text: "Ciliegie" },
      { id: "C", text: "Ciliegia" },
      { id: "D", text: "Ciliegii" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Il plurale più corretto e comune è ciliegie.",
  },
  {
    id: "gen_092",
    category: "general",
    subcategory: "grammatica-italiana",
    text: "Quale tra queste parole è un verbo?",
    answers: [
      { id: "A", text: "Cantare" },
      { id: "B", text: "Canto" },
      { id: "C", text: "Cantante" },
      { id: "D", text: "Canzone" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Cantare è un verbo all'infinito.",
  },
  {
    id: "gen_093",
    category: "general",
    subcategory: "grammatica-italiana",
    text: "Quale segno di punteggiatura indica normalmente una domanda?",
    answers: [
      { id: "A", text: "Punto" },
      { id: "B", text: "Virgola" },
      { id: "C", text: "Punto interrogativo" },
      { id: "D", text: "Due punti" },
    ],
    correctAnswerIds: ["C"],
    explanation: "Il punto interrogativo si usa per concludere una frase interrogativa diretta.",
  },
  {
    id: "gen_094",
    category: "general",
    subcategory: "grammatica-italiana",
    text: "Quale parola contiene un accento grafico corretto?",
    answers: [
      { id: "A", text: "Perche" },
      { id: "B", text: "Perché" },
      { id: "C", text: "Percè" },
      { id: "D", text: "Pèrche" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Perché si scrive con l'accento acuto finale.",
  },
  {
    id: "gen_095",
    category: "general",
    subcategory: "grammatica-italiana",
    text: "Nella frase 'Il gatto dorme', qual è il soggetto?",
    answers: [
      { id: "A", text: "Il gatto" },
      { id: "B", text: "Dorme" },
      { id: "C", text: "Il" },
      { id: "D", text: "Gatto dorme" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Il soggetto è 'Il gatto', cioè chi compie l'azione di dormire.",
  },
  {
    id: "gen_096",
    category: "general",
    subcategory: "matematica",
    text: "Quanto fa 15 + 27?",
    answers: [
      { id: "A", text: "32" },
      { id: "B", text: "40" },
      { id: "C", text: "42" },
      { id: "D", text: "52" },
    ],
    correctAnswerIds: ["C"],
    explanation: "15 + 27 = 42.",
  },
  {
    id: "gen_097",
    category: "general",
    subcategory: "matematica",
    text: "Qual è la metà di 90?",
    answers: [
      { id: "A", text: "35" },
      { id: "B", text: "40" },
      { id: "C", text: "45" },
      { id: "D", text: "50" },
    ],
    correctAnswerIds: ["C"],
    explanation: "La metà di 90 è 45.",
  },
  {
    id: "gen_098",
    category: "general",
    subcategory: "matematica",
    text: "Quanti gradi misura un angolo retto?",
    answers: [
      { id: "A", text: "45" },
      { id: "B", text: "90" },
      { id: "C", text: "180" },
      { id: "D", text: "360" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Un angolo retto misura 90 gradi.",
  },
  {
    id: "gen_099",
    category: "general",
    subcategory: "matematica",
    text: "Quanto fa 7 x 8?",
    answers: [
      { id: "A", text: "54" },
      { id: "B", text: "56" },
      { id: "C", text: "58" },
      { id: "D", text: "64" },
    ],
    correctAnswerIds: ["B"],
    explanation: "7 moltiplicato per 8 fa 56.",
  },
  {
    id: "gen_100",
    category: "general",
    subcategory: "matematica",
    text: "Quale numero viene subito dopo 999?",
    answers: [
      { id: "A", text: "100" },
      { id: "B", text: "990" },
      { id: "C", text: "1000" },
      { id: "D", text: "1001" },
    ],
    correctAnswerIds: ["C"],
    explanation: "Dopo 999 viene 1000.",
  },
  {
    id: "gen_101",
    category: "general",
    subcategory: "fisica-chimica",
    text: "Quale gas respiriamo principalmente per vivere?",
    answers: [
      { id: "A", text: "Ossigeno" },
      { id: "B", text: "Elio" },
      { id: "C", text: "Idrogeno" },
      { id: "D", text: "Neon" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Il corpo umano usa l'ossigeno per produrre energia nelle cellule.",
  },
  {
    id: "gen_102",
    category: "general",
    subcategory: "fisica-chimica",
    text: "A quale temperatura bolle l'acqua al livello del mare?",
    answers: [
      { id: "A", text: "50 °C" },
      { id: "B", text: "75 °C" },
      { id: "C", text: "100 °C" },
      { id: "D", text: "150 °C" },
    ],
    correctAnswerIds: ["C"],
    explanation: "Al livello del mare l'acqua bolle a circa 100 °C.",
  },
  {
    id: "gen_103",
    category: "general",
    subcategory: "fisica-chimica",
    text: "Quale forza ci tiene attaccati alla Terra?",
    answers: [
      { id: "A", text: "Magnetismo" },
      { id: "B", text: "Gravità" },
      { id: "C", text: "Elettricità" },
      { id: "D", text: "Attrito" },
    ],
    correctAnswerIds: ["B"],
    explanation: "La gravità è la forza di attrazione che ci tiene sulla superficie terrestre.",
  },
  {
    id: "gen_104",
    category: "general",
    subcategory: "fisica-chimica",
    text: "Quale organo pompa il sangue nel corpo umano?",
    answers: [
      { id: "A", text: "Cuore" },
      { id: "B", text: "Polmone" },
      { id: "C", text: "Stomaco" },
      { id: "D", text: "Fegato" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Il cuore pompa il sangue attraverso arterie e vene.",
  },
  {
    id: "gen_105",
    category: "general",
    subcategory: "fisica-chimica",
    text: "Quale stato della materia ha forma e volume propri?",
    answers: [
      { id: "A", text: "Gas" },
      { id: "B", text: "Liquido" },
      { id: "C", text: "Solido" },
      { id: "D", text: "Vapore" },
    ],
    correctAnswerIds: ["C"],
    explanation: "Un solido mantiene sia la forma sia il volume.",
  },
  {
    id: "gen_106",
    category: "general",
    subcategory: "arte",
    text: "Chi dipinse La notte stellata?",
    answers: [
      { id: "A", text: "Vincent van Gogh" },
      { id: "B", text: "Pablo Picasso" },
      { id: "C", text: "Claude Monet" },
      { id: "D", text: "Salvador Dalì" },
    ],
    correctAnswerIds: ["A"],
    explanation: "La notte stellata è uno dei dipinti più celebri di Vincent van Gogh.",
  },
  {
    id: "gen_107",
    category: "general",
    subcategory: "arte",
    text: "Quale artista è famoso per il Cubismo insieme a Georges Braque?",
    answers: [
      { id: "A", text: "Pablo Picasso" },
      { id: "B", text: "Caravaggio" },
      { id: "C", text: "Giotto" },
      { id: "D", text: "Canaletto" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Picasso e Braque sono tra i principali fondatori del Cubismo.",
  },
  {
    id: "gen_108",
    category: "general",
    subcategory: "arte",
    text: "In quale città si trova il museo del Louvre?",
    answers: [
      { id: "A", text: "Londra" },
      { id: "B", text: "Parigi" },
      { id: "C", text: "Madrid" },
      { id: "D", text: "Vienna" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Il Louvre si trova a Parigi ed è uno dei musei più visitati al mondo.",
  },
  {
    id: "gen_109",
    category: "general",
    subcategory: "arte",
    text: "Chi scrisse I promessi sposi?",
    answers: [
      { id: "A", text: "Giacomo Leopardi" },
      { id: "B", text: "Alessandro Manzoni" },
      { id: "C", text: "Italo Calvino" },
      { id: "D", text: "Giovanni Verga" },
    ],
    correctAnswerIds: ["B"],
    explanation: "I promessi sposi è il romanzo più celebre di Alessandro Manzoni.",
  },
  {
    id: "gen_110",
    category: "general",
    subcategory: "arte",
    text: "Quale pittore italiano è noto per il forte uso del chiaroscuro?",
    answers: [
      { id: "A", text: "Caravaggio" },
      { id: "B", text: "Botticelli" },
      { id: "C", text: "Tiziano" },
      { id: "D", text: "Raffaello" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Caravaggio è famoso per l'uso drammatico della luce e del buio.",
  },
  {
    id: "gen_111",
    category: "general",
    subcategory: "musica",
    text: "Quanti tasti bianchi e neri ha di solito un pianoforte moderno?",
    answers: [
      { id: "A", text: "66" },
      { id: "B", text: "76" },
      { id: "C", text: "88" },
      { id: "D", text: "100" },
    ],
    correctAnswerIds: ["C"],
    explanation: "Il pianoforte moderno standard ha 88 tasti.",
  },
  {
    id: "gen_112",
    category: "general",
    subcategory: "musica",
    text: "Quale strumento suona un violinista?",
    answers: [
      { id: "A", text: "Violino" },
      { id: "B", text: "Flauto" },
      { id: "C", text: "Tromba" },
      { id: "D", text: "Batteria" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Un violinista suona il violino.",
  },
  {
    id: "gen_113",
    category: "general",
    subcategory: "musica",
    text: "Chi è conosciuto come il Re del Pop?",
    answers: [
      { id: "A", text: "Elvis Presley" },
      { id: "B", text: "Michael Jackson" },
      { id: "C", text: "Freddie Mercury" },
      { id: "D", text: "Prince" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Michael Jackson è comunemente chiamato il Re del Pop.",
  },
  {
    id: "gen_114",
    category: "general",
    subcategory: "musica",
    text: "Quale cantante italiana è soprannominata la Tigre di Cremona?",
    answers: [
      { id: "A", text: "Mina" },
      { id: "B", text: "Raffaella Carrà" },
      { id: "C", text: "Laura Pausini" },
      { id: "D", text: "Giorgia" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Mina è soprannominata la Tigre di Cremona.",
  },
  {
    id: "gen_115",
    category: "general",
    subcategory: "musica",
    text: "Quale famiglia di strumenti comprende il flauto?",
    answers: [
      { id: "A", text: "Archi" },
      { id: "B", text: "Fiati" },
      { id: "C", text: "Percussioni" },
      { id: "D", text: "Tastiere" },
    ],
    correctAnswerIds: ["B"],
    explanation: "Il flauto appartiene alla famiglia degli strumenti a fiato.",
  },
  {
    id: "gen_116",
    category: "general",
    subcategory: "religione",
    text: "Quale città è considerata santa da ebraismo, cristianesimo e islam?",
    answers: [
      { id: "A", text: "Gerusalemme" },
      { id: "B", text: "Atene" },
      { id: "C", text: "Roma" },
      { id: "D", text: "Istanbul" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Gerusalemme ha un ruolo religioso centrale per ebraismo, cristianesimo e islam.",
  },
  {
    id: "gen_117",
    category: "general",
    subcategory: "religione",
    text: "Come si chiama il mese di digiuno nella tradizione islamica?",
    answers: [
      { id: "A", text: "Ramadan" },
      { id: "B", text: "Avvento" },
      { id: "C", text: "Quaresima" },
      { id: "D", text: "Hanukkah" },
    ],
    correctAnswerIds: ["A"],
    explanation: "Il Ramadan è il mese sacro di digiuno e preghiera per i musulmani.",
  },
  {
    id: "gen_118",
    category: "general",
    subcategory: "religione",
    text: "Qual è il luogo di culto principale dei cristiani?",
    answers: [
      { id: "A", text: "Sinagoga" },
      { id: "B", text: "Moschea" },
      { id: "C", text: "Chiesa" },
      { id: "D", text: "Tempio shintoista" },
    ],
    correctAnswerIds: ["C"],
    explanation: "Il luogo di culto cristiano è generalmente chiamato chiesa.",
  },
  {
    id: "gen_119",
    category: "general",
    subcategory: "religione",
    text: "Quale religione usa spesso il simbolo della ruota del Dharma?",
    answers: [
      { id: "A", text: "Buddismo" },
      { id: "B", text: "Cristianesimo" },
      { id: "C", text: "Islam" },
      { id: "D", text: "Ebraismo" },
    ],
    correctAnswerIds: ["A"],
    explanation: "La ruota del Dharma è un simbolo importante del Buddismo.",
  },
  {
    id: "gen_120",
    category: "general",
    subcategory: "religione",
    text: "Come si chiama il libro sacro principale del cristianesimo?",
    answers: [
      { id: "A", text: "Bibbia" },
      { id: "B", text: "Corano" },
      { id: "C", text: "Veda" },
      { id: "D", text: "Tao Te Ching" },
    ],
    correctAnswerIds: ["A"],
    explanation: "La Bibbia è il testo sacro principale del cristianesimo.",
  },
];
